### ISSUE TITLE
Getting error msg on running

### ISSUE THREAD

**Issue by twlatl** [bodnaristvan/JavascriptHinter.tmbundle#7]
I'm getting an error msg on running this on a JS file:

`events.js:85 throw er; // Unhandled 'error' event ^ Error: spawn jshint ENOENT at exports._errnoException (util.js:746:11) at Process.ChildProcess._handle.onexit (child_process.js:1053:32) at child_process.js:1144:20 at process._tickCallback (node.js:355:11) at Function.Module.runMain (module.js:503:11) at startup (node.js:129:16) at node.js:814:3`

I do have Node installed (v0.12.7)
I have JSHint installed (jshint v2.8.0)
I have jscs installed (2.1.1)

Running TextMate version 2.0-beta.7.9

**Comment by bodnaristvan** [comment]
Hey @serpicolugnut, totally missed this issue..

I believe the problem here is that your jshint executable is installed in a location that is not in the `$PATH` of TextMate -- afaik it still uses it's own `$PATH` when executing bundle commands.

To set the correct path make sure that jshint's parent directory is included in the settings:
<img width="921" alt="screenshot 2015-11-19 10 53 54" src="https://cloud.githubusercontent.com/assets/710358/11267493/f9706dc0-8eab-11e5-8b16-1cad5a10214b.png">

To get jshints parent dir just use the `which` shell command:

```
dig:~$ which jshint
/opt/boxen/nodenv/shims/jshint
```

Let me know if that did not help!
